#!/usr/bin/env bash
set -euo pipefail

echo "=== Setting up .env ==="
cat > .env <<EOF
# Outreach System — Environment Configuration
# Auto-generated by GitHub Actions
GOOGLE_MAPS_API_KEY="${GOOGLE_MAPS_API_KEY}"
GEMINI_API_KEY="${GEMINI_API_KEY}"
SPREADSHEET_ID="${SPREADSHEET_ID}"
SENDER_NAME="${SENDER_NAME}"
SENDER_EMAIL="${SENDER_EMAIL}"
WARMUP_START_DATE="${WARMUP_START_DATE}"
EOF

echo "=== Setting up credentials.json ==="
echo "${CREDENTIALS_JSON}" > credentials.json

echo "=== Setting up token.json ==="
echo "${GMAIL_TOKEN_JSON}" > token.json

echo "=== Setting up sheets_token.json ==="
echo "${SHEETS_TOKEN_JSON}" > sheets_token.json

echo "=== Setup complete ==="
ls -la .env credentials.json token.json sheets_token.json
